<?xml version='1.0' encoding='UTF-8'?>
<testsuite hostname="asus510" name="vonsim.simulator.SimulatorSuite" tests="6" errors="0" failures="3" time="0.051">
                     <properties>
      <property name="jline.esc.timeout" value="0"/><property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/><property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/><property name="java.vm.version" value="25.121-b13"/><property name="java.vm.vendor" value="Oracle Corporation"/><property name="java.vendor.url" value="http://java.oracle.com/"/><property name="path.separator" value=":"/><property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/><property name="file.encoding.pkg" value="sun.io"/><property name="user.country" value="US"/><property name="sun.java.launcher" value="SUN_STANDARD"/><property name="sun.os.patch.level" value="unknown"/><property name="java.vm.specification.name" value="Java Virtual Machine Specification"/><property name="user.dir" value="/data/dev/vonsim"/><property name="java.runtime.version" value="1.8.0_121-b13"/><property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/><property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/><property name="os.arch" value="amd64"/><property name="java.io.tmpdir" value="/tmp"/><property name="line.separator" value="
"/><property name="java.vm.specification.vendor" value="Oracle Corporation"/><property name="os.name" value="Linux"/><property name="sun.jnu.encoding" value="UTF-8"/><property name="java.library.path" value="/usr/local/cuda/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/><property name="java.specification.name" value="Java Platform API Specification"/><property name="java.class.version" value="52.0"/><property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/><property name="os.version" value="4.4.0-42-generic"/><property name="user.home" value="/home/facundoq"/><property name="user.timezone" value="America/Argentina/Buenos_Aires"/><property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/><property name="file.encoding" value="UTF-8"/><property name="java.specification.version" value="1.8"/><property name="java.class.path" value="/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar"/><property name="user.name" value="facundoq"/><property name="jline.shutdownhook" value="false"/><property name="java.vm.specification.version" value="1.8"/><property name="sun.java.command" value="/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar"/><property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/><property name="sun.arch.data.model" value="64"/><property name="user.language" value="en"/><property name="java.specification.vendor" value="Oracle Corporation"/><property name="awt.toolkit" value="sun.awt.X11.XToolkit"/><property name="java.vm.info" value="mixed mode"/><property name="java.version" value="1.8.0_121"/><property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/><property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/><property name="java.vendor" value="Oracle Corporation"/><property name="file.separator" value="/"/><property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/><property name="sun.io.unicode.encoding" value="UnicodeLittle"/><property name="sun.cpu.endian" value="little"/><property name="sun.cpu.isalist" value=""/>
    </properties>
                     <testcase classname="vonsim.simulator.SimulatorSuite" name="3+2=5 register" time="0.014">
                                                 
                                               </testcase><testcase classname="vonsim.simulator.SimulatorSuite" name="3+2=5 memory" time="0.007">
                                                 
                                               </testcase><testcase classname="vonsim.simulator.SimulatorSuite" name="3+3=6 memory/register" time="0.007">
                                                 
                                               </testcase><testcase classname="vonsim.simulator.SimulatorSuite" name="3+1=4" time="0.007">
                                                 <failure message="Expected 4, but got 0" type="org.scalajs.testadapter.RemoteException">org.scalatest.exceptions.TestFailedException: Expected 4, but got 0
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:33)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.init___T__jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_RuntimeException.init___jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalanglib/src/main/scala/java/lang/Throwables.scala:342)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_Lorg_scalatest_exceptions_StackDepthException.init___F1__s_Option__s_util_Either(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/StackDepthException.scala:42)
	at org.scalatest.exceptions.TestFailedException.&lt;init&gt;(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/TestFailedException.scala:54)
	at org.scalatest.exceptions.TestFailedException.&lt;init&gt;(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/TestFailedException.scala:78)
	at org.scalatest.Assertions$class.newAssertionFailedException(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/Assertions.scala:528)
	at org.scalatest.Assertions$class.assertResult(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/Assertions.scala:1020)
	at &lt;jscode&gt;.{anonymous}()(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/FunSuite.scala:1560)
	at scala.scalajs.runtime.AnonFunction0.apply(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:10)
</failure>
                                               </testcase><testcase classname="vonsim.simulator.SimulatorSuite" name="3-1=2" time="0.009">
                                                 <failure message="Expected 2, but got 0" type="org.scalajs.testadapter.RemoteException">org.scalatest.exceptions.TestFailedException: Expected 2, but got 0
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:33)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.init___T__jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_RuntimeException.init___jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalanglib/src/main/scala/java/lang/Throwables.scala:342)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_Lorg_scalatest_exceptions_StackDepthException.init___F1__s_Option__s_util_Either(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/StackDepthException.scala:42)
	at org.scalatest.exceptions.TestFailedException.&lt;init&gt;(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/TestFailedException.scala:54)
	at org.scalatest.exceptions.TestFailedException.&lt;init&gt;(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/TestFailedException.scala:78)
	at org.scalatest.Assertions$class.newAssertionFailedException(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/Assertions.scala:528)
	at org.scalatest.Assertions$class.assertResult(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/Assertions.scala:1020)
	at &lt;jscode&gt;.{anonymous}()(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/FunSuite.scala:1560)
	at scala.scalajs.runtime.AnonFunction0.apply(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:10)
</failure>
                                               </testcase><testcase classname="vonsim.simulator.SimulatorSuite" name="push pop" time="0.007">
                                                 <failure message="Expected 2, but got 3" type="org.scalajs.testadapter.RemoteException">org.scalatest.exceptions.TestFailedException: Expected 2, but got 3
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:33)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.init___T__jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_RuntimeException.init___jl_Throwable(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalanglib/src/main/scala/java/lang/Throwables.scala:342)
	at &lt;jscode&gt;.$c_Lorg_scalatest_exceptions_TestFailedException.$c_Lorg_scalatest_exceptions_StackDepthException.init___F1__s_Option__s_util_Either(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/StackDepthException.scala:42)
	at org.scalatest.exceptions.TestFailedException.&lt;init&gt;(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/TestFailedException.scala:54)
	at org.scalatest.exceptions.TestFailedException.&lt;init&gt;(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/exceptions/TestFailedException.scala:78)
	at org.scalatest.Assertions$class.newAssertionFailedException(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/Assertions.scala:528)
	at org.scalatest.Assertions$class.assertResult(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/Assertions.scala:1020)
	at &lt;jscode&gt;.{anonymous}()(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scalatest/scalatest/v3.0.0/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/FunSuite.scala:1560)
	at scala.scalajs.runtime.AnonFunction0.apply(/data/dev/vonsim/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.14/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:10)
</failure>
                                               </testcase>
                     <system-out></system-out>
                     <system-err></system-err>
                   </testsuite>